version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tickets
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

  rest-api:
    build:
      dockerfile: Dockerfile
      context: ./rest
    container_name: rest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork
    restart: always
    volumes:
      - .:/app
      - /app/rest/node_modules

  grpc-server:
    build:
      context: ./grpc
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - mynetwork

  graphql-server:
    build:
      context: ./graphql
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
