version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  rest-api:
    build:
      context: ./rest-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  grpc-server:
    build:
      context: ./grpc-server
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - mynetwork

  graphql-server:
    build:
      context: ./graphql-server
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
